### ISSUE TITLE
Broken with Blender 2.8

### ISSUE THREAD

**Issue by biller23** [V0idExp/blender-bullet-export#1]
Unfortunately, Blender 2.8 dropped support for the BGE, a dependency of this add-on.

**Comment by V0idExp** [comment]
The script relies on some internal data related to Bullet, I'd have to check what is the current state of things, but it was a while that I didn't use Blender. Even forgot I had this script on GitHub :D

**Comment by biller23** [comment]
Thank you for the answer!

This little add-on was very neat for exporting rigid bodies quick and easy, included the compound shapes in BGE.
It is unfortunate that Blender is still heavily oriented toward non-interactive applications.
For example, now that that BGE is gone, there is no "compound" option. Blender just prefer to emulate compound shapes by just creating a lot of rigid bodies and adding constraints between them apparently...

The majority of game engines expect collision data to be recreated later inside of them, but I would prefer the ability to use blender to export physics data in sync with modeling.

**Comment by biller23** [comment]
I think I will close this issue. I think it is not worth anyone's time. I found another add-on to simply export a .json, that is a viable workaround. Thank you anyway. Cheers!

**Comment by bdotq** [comment]
> 
> 
> I think I will close this issue. I think it is not worth anyone's time. I found another add-on to simply export a .json, that is a viable workaround. Thank you anyway. Cheers!

Could you happen to mention this other addon? may be very handy for some others too

**Comment by biller23** [comment]
> 
> 
> > I think I will close this issue. I think it is not worth anyone's time. I found another add-on to simply export a .json, that is a viable workaround. Thank you anyway. Cheers!
> 
> Could you happen to mention this other addon? may be very handy for some others too

Sure. I use a modified version of  xu-xionglong/bullet-blender-exporter:
https://github.com/biller23/bullet-blender-exporter

It is easy exporting JSON from blender and you can easily modify the script of the addon (python). If you need a good JSON lib for c/c++, there is cJSON.
